"""
TS-INTERCOM-01..03 — INTERCOM scenarios.

INTERCOM is an RSA-encrypted peer-to-peer routing message. The master routes it
to the target identified by target_public_key. When target_public_key is not set
or does not match any known destination, the message falls through silently.

Protocol path:
  satellite → HiveMessage(INTERCOM, payload=..., target_pubkey=<key>)
  master:     handle_intercom_message()
              - if target_pubkey is not set or doesn't match master's pubkey → return False
              - if target_pubkey matches master: decrypt payload with master's private key
  In BROADCAST/PROPAGATE/ESCALATE wrappers:
              - inner INTERCOM is checked; if not routed to master → normal fan-out proceeds

Note: make_identity() generates a fresh RSA keypair (2048-bit) for every node.
      The private key is stored at identity.private_key (PEM path).
      The public key is stored at identity.public_key (ASCII-armored string).
"""
import json
import pytest
import pybase64
from ovos_bus_client.message import Message
from hivemind_bus_client.message import HiveMessage, HiveMessageType
from hivescope.topology import TopologyBuilder
from hivescope.node import MasterNode, SatelliteNode


def _intercom_msg(target_pubkey=None):
    """Build a bare INTERCOM HiveMessage (unencrypted, for no-crash tests)."""
    inner = HiveMessage(HiveMessageType.BUS,
                        payload=Message("test.intercom", {"data": "hello"}))
    return HiveMessage(HiveMessageType.INTERCOM, payload=inner.as_dict,
                       target_pubkey=target_pubkey)


class TestIntercomNoEncryption:
    """TS-INTERCOM-01 — INTERCOM without encryption does not crash the master."""

    def test_unencrypted_intercom_no_target_does_not_crash(self, minimal_topology):
        """INTERCOM with no target_pubkey and no ciphertext → falls to handle_unknown_message."""
        b = minimal_topology
        s0 = b.get_satellite("S0")
        m0 = b.get_master("M0")

        # No target_pubkey → handle_intercom_message skips decryption,
        # inner msg_type is not a top-level type after decrypt → returns False → handle_unknown_message
        msg = _intercom_msg(target_pubkey=None)
        # Should not raise
        s0.send(msg)

        # Master recorded the inbound INTERCOM
        m0.recorder.assert_received(HiveMessageType.INTERCOM, direction="in")

    def test_intercom_with_unknown_pubkey_does_not_crash(self, minimal_topology):
        """INTERCOM targeting an unknown pubkey is silently dropped (not for this master)."""
        b = minimal_topology
        s0 = b.get_satellite("S0")
        m0 = b.get_master("M0")

        msg = _intercom_msg(target_pubkey="not-a-real-key")
        # Should not raise — master returns False (not for us) → handle_unknown_message
        s0.send(msg)

        m0.recorder.assert_received(HiveMessageType.INTERCOM, direction="in")

    @pytest.mark.xfail(
        reason="hivemind-websocket-client#130: handle_intercom asserts "
               "message.payload.msg_type and crashes (AttributeError) on a "
               "dict/opaque INTERCOM payload instead of ignoring it.",
        strict=False,
    )
    def test_intercom_in_broadcast_does_not_crash(self, admin_star_topology):
        """BROADCAST wrapping INTERCOM from admin satellite → master tries INTERCOM routing,
        fails silently (no matching key), then proceeds with normal broadcast fan-out."""
        b = admin_star_topology
        m0 = b.get_master("M0")
        s0 = b.get_satellite("S0")  # admin
        s1 = b.get_satellite("S1")

        intercom = _intercom_msg(target_pubkey="unknown-key")
        broadcast = HiveMessage(HiveMessageType.BROADCAST, payload=intercom)

        s1_received = []
        s1.shim.emitter.on(HiveMessageType.BROADCAST, s1_received.append)

        # Should not raise
        s0.send(broadcast)

        # INTERCOM routing fails (unknown key), so normal broadcast fan-out proceeds
        assert len(s1_received) == 1, \
            "After INTERCOM routing fails, BROADCAST fan-out must still reach siblings"


class TestIntercomRSA:
    """TS-INTERCOM-02 — RSA-encrypted INTERCOM targeting master's public key.

    Every node identity has a fresh RSA keypair generated by make_identity() via
    HandShake. We can encrypt a payload with the master's public key and send it
    as INTERCOM — the master should decrypt it with its private key.

    Note: handle_intercom_message() decrypts the payload but then checks
    message.msg_type (which is always INTERCOM) against BUS/PROPAGATE/etc.
    This means the inner-message dispatch after decryption currently returns
    False unconditionally (the outer INTERCOM msg_type never matches).
    These tests document that limitation and verify the decrypt path is reached
    without crashing.
    """

    def test_intercom_targeting_master_does_not_crash(self, minimal_topology):
        """RSA-encrypted INTERCOM targeting master's pubkey is decrypted without crashing."""
        from poorman_handshake.asymmetric.utils import encrypt_RSA, load_RSA_key

        b = minimal_topology
        s0 = b.get_satellite("S0")
        m0 = b.get_master("M0")

        # Build the inner payload to encrypt
        inner = HiveMessage(HiveMessageType.BUS,
                            payload=Message("test.intercom.rsa", {"secret": "42"}))
        inner_json = inner.serialize()

        # Load master's private key from PEM file, derive public key from it
        master_privkey = load_RSA_key(m0.identity.private_key)
        master_pubkey = master_privkey.publickey()
        ciphertext = encrypt_RSA(master_pubkey, inner_json.encode("utf-8"))
        signature = b""  # signature verification is a TODO in the protocol

        encrypted_payload = {
            "ciphertext": pybase64.b64encode(ciphertext).decode("utf-8"),
            "signature": pybase64.b64encode(signature).decode("utf-8"),
        }

        msg = HiveMessage(HiveMessageType.INTERCOM,
                          payload=encrypted_payload,
                          target_pubkey=m0.identity.public_key)

        # Should not raise — master decrypts with its private key
        s0.send(msg)

        m0.recorder.assert_received(HiveMessageType.INTERCOM, direction="in")
